# Generated by Django 2.1.5 on 2019-02-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190210_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank='True', max_length=150, unique=True),
        ),
    ]
